<?php

/**
 *
 * @file
 * Primary module hooks for marketplacehbk module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\taxonomy\Entity\Vocabulary;

/**
 * Implement hook_entity_base_field_info
 *
 * @param EntityTypeInterface $entity_type
 */
function marketplacehbk_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() == 'commerce_product') {
    /**
     * On ajoute un champs durée de traiement en jour.
     * Cette valeur serra ajouter sur celle determiner par le plugin de
     * livraison.
     */
    $fields["hbk_duree_traitement"] = BaseFieldDefinition::create('integer')->setLabel(" Durée traitement supplementaire en heures ")->setRevisionable(TRUE)->setSettings([
      'min' => 0
    ])->setDisplayOptions('view', [
      'label' => 'above',
      'type' => 'marketplacehbk_shipping_estimation',
      'weight' => -4
    ])->setDisplayOptions('form', [
      'type' => 'number'
    ])->setDisplayConfigurable('form', TRUE)->setDisplayConfigurable('view', TRUE)->setDefaultValue(0)->setDescription(
      "Definissez une durée supplementaire qui s'ajoutera à la valeur de livraison par defaut");
  }
  return $fields;
}

/**
 * implement hook_commerce_checkout_pane_info_alter
 *
 * @param array $definitions
 */
// function marketplacehbk_commerce_checkout_pane_info_alter(&$definitions) {
// // \Drupal::messenger()->addStatus("run
// // stripebyhabeuk_commerce_checkout_pane_info_alter");
// // dump("stripebyhabeuk_commerce_checkout_pane_info_alter");
// // \Stephane888\Debug\debugLog::kintDebugDrupal($definitions,
// // 'stripebyhabeuk_commerce_checkout_pane_info_alter', true);
// }

/**
 * Pour faciliter utilisation des vocabulaire dans l'administration
 * Implement hook_form_FORM_ID_alter
 */
function marketplacehbk_form_field_config_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  /**
   * Ajoute la description devant chaque terme afin qu'on puisse identifier
   * facilement le terme.
   */
  // dump($form);
  if (!empty($form['default_value']['widget'][0]['target_id']['#target_type']) && $form['default_value']['widget'][0]['target_id']['#target_type'] == 'taxonomy_term' && !empty(
    $form['settings']['handler']['handler_settings']['target_bundles']['#options'])) {
    foreach ($form['settings']['handler']['handler_settings']['target_bundles']['#options'] as $k => $value) {
      $voc = Vocabulary::load($k);
      if ($voc) {
        $form['settings']['handler']['handler_settings']['target_bundles']['#options'][$k] = $value . ' >> ' . $voc->getDescription();
      }
    }
  }
  elseif (!empty($form['default_value']['widget']['#target_type']) && $form['default_value']['widget']['#target_type'] == 'taxonomy_term' && !empty(
    $form['settings']['handler']['handler_settings']['target_bundles']['#options'])) {
    foreach ($form['settings']['handler']['handler_settings']['target_bundles']['#options'] as $k => $value) {
      $voc = Vocabulary::load($k);
      if ($voc) {
        $form['settings']['handler']['handler_settings']['target_bundles']['#options'][$k] = $value . ' >> ' . $voc->getDescription();
      }
    }
  }
}